### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DenielWorld** [ElementalMinecraftGaming/EmeraldWarp#1]
You should make it so you need a specific item to warp to that zone. (Have the price set to an item)

**Comment by ElementalMinecraftGaming** [comment]
I will take this into consideration.

**Comment by ElementalMinecraftGaming** [comment]
> You should make it so you need a specific item to warp to that zone. (Have the price set to an item)

Your idea has been accepted as a separate warp style that you can create and will hopefully be in the next update.
