### ISSUE TITLE
permisson

### ISSUE THREAD

**Issue by mikeygio10** [ElementalMinecraftGaming/EmeraldWarp#2]
is there a way to set a pureperms perm or like a rankup perm or something so only certain player can use

**Comment by ElementalMinecraftGaming** [comment]
Look at the README or poggit page where the permissions are shown where you can use pureperms to stop certain players using commands

**Comment by mikeygio10** [comment]
no like per warp

**Comment by mikeygio10** [comment]
So that player can only use a specific warp then use all like kitUI plugin has it so you have to give non ops a perm like if the kit was named starterkit you would do with pureperms /setgperm {Rank} kit.starterkit

**Comment by ElementalMinecraftGaming** [comment]
I don't think I can add this as of right now.
Maybe in the future though.
