### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BootheBoys** [ElementalMinecraftGaming/EmeraldWarp#3]
Can't get it to work at all. Looked at "read me" and all the commands, and I cannot set a warp. Also, you have this: "/esetwarp {warp} {PriceOrItemID} {Config}" and nobody knows what to put in "{config}. Need to explain that once you make it to where warps do work.

**Comment by ElementalMinecraftGaming** [comment]
You should know if you got it from where it is published and did not use a dev build.
Only used published builds where it states quite plainly what all this is. 

poggit.pmmp.io/p/EmeraldWarp

**Comment by BootheBoys** [comment]
What is wrong with these commands then:
"/esetwarp nether 372"
"/esetwarp nether"

The point of my comment was the fact that either your plugin does not work, or it is not explained correctly of how to use it.

**Comment by ElementalMinecraftGaming** [comment]
You need to read the description for the description to tell you how to use it.
You obviously didn't.
